import '@style/globals.css'


export const metadata = {
  title: 'nike',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
export default RootLayout
